display: ":0"
xauthority: "~/.Xauthority"
legacy_compatibility: true

global:
  minikube: true
  sub-system:
    ska-tango-base:
      enabled: false
  tango_host: databaseds-tango-base-test:10000
  retry:
    - "--tries=10"
    - "--sleep=5"
  dishes: ["ska001", "ska002"]
  mid_sdp_queueconnector: "mid-sdp/queueconnector/01"
  dish_manager_suffix: "mid-dish/dish-manager/ska"
  DEBUG: 5678

ska-tango-base:
  vnc:
    enabled: false
  tangorest:
    enabled: false
  ingress:
    enabled: false
  tangodb:
    use_pv: false
  itango:
    enabled: true
  jive:
    enabled: false

tmc-dishleafnode:
  deviceServers:
    dishln:
      enabled: true
      IsDishAbortEnabled: True
      MaxTrackTableRetry: 3
      TrackTableRetryDuration: 0.2
      source_uris: "gitlab://gitlab.com/ska-telescope/ska-telmodel-data?main#tmdata"
      array_layout_path: "instrument/ska1_mid/layout/mid-layout.json"
    dishpointingdevice:
      TrackTableUpdateRate: 50
      TrackTableInAdvance: 6
      Elevation: 30.0
      Azimuth: 0.0
      ElevationMaxLimit: 90.0
      ElevationMinLimit: 15.0
      AzimuthMinLimit: -270.0
      AzimuthMaxLimit: 270.0
      SchedularQueuePreEntries: 5

ska-tmc-simulators:
  enabled: true
  ska_tmc_simulators:
    image:
      registry: registry.gitlab.com/ska-telescope/ska-tmc/ska-tmc-simulators
      image: ska-tmc-simulators
      tag: 1.9.0-dev.c04074d2c
  telescope: SKA-mid
  deviceServers:
    mocks:
      enabled: true
      mid:
        is_simulated:
          csp: false

ska-taranta:
  enabled: false
