display: ":0"
xauthority: "~/.Xauthority"

enabled: true

system: SW-infrastructure
subsystem: ska-tmc-dishleafnode
telescope: SKA-mid
legacy_compatibility: true

labels:
  app: ska-tmc-dishleafnode

global:
  minikube: true
  tango_host: databaseds-tango-base-test:10000
  retry:
  - "--tries=10"
  - "--sleep=5"
  dish_devices:
    - "dishleafnode"
  dishes: ["01", "02", "03", "04"]
  instances : ["01", "02", "03", "04"]

dsconfig:
  configuration_file: data/configuration.json
  timeout: 300s
  image:
      registry: artefact.skao.int
      image: ska-tango-images-tango-dsconfig
      tag: 1.5.5
      pullPolicy: IfNotPresent

itango:
  image:
    registry: artefact.skao.int
    image: ska-tango-images-tango-itango
    tag: 9.3.9
    pullPolicy: IfNotPresent

dishleafnode:
  image:
    registry: artefact.skao.int
    image: ska-tmc-dishleafnode
    tag: 0.10.0
    pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 500m
    memory: 500Mi
  requests:
    cpu: 500m
    memory: 500Mi

deviceServers:
  mocks:
    enabled: true
    instances: ["01", "02", "03", "04"]
    file: "data/mockdevices.yaml"
  dishln:
    enabled: true
    instances: ["01", "02", "03", "04"]
    file: "data/dishleafnode.yaml"
    TrackTableEntries: 25
    PointingCalculationPeriod: 100

nodeSelector: {}

affinity: {}

tolerations: []
